# -*- coding: utf-8 -*-
"""Oop_zad.2

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1Xc_0fMvExW9RG5uC34S7XPH3ULvHBXWg
"""

class Library:
    def __init__(self, city, street, zip_code, open_hours, phone):
        self.city = city
        self.street = street
        self.zip_code = zip_code
        self.open_hours = open_hours
        self.phone = phone

    def __str__(self):
        return f"Library: {self.city}, {self.street}, {self.zip_code}, {self.open_hours}, {self.phone}"


class Employee:
    def __init__(self, first_name, last_name, hire_date, birth_date, city, street, zip_code, phone):
        self.first_name = first_name
        self.last_name = last_name
        self.hire_date = hire_date
        self.birth_date = birth_date
        self.city = city
        self.street = street
        self.zip_code = zip_code
        self.phone = phone

    def __str__(self):
        return f"Employee: {self.first_name} {self.last_name}, {self.hire_date}, {self.birth_date}, " \
               f"{self.city}, {self.street}, {self.zip_code}, {self.phone}"


class Book:
    def __init__(self, library, publication_date, author_name, author_surname, number_of_pages):
        self.library = library
        self.publication_date = publication_date
        self.author_name = author_name
        self.author_surname = author_surname
        self.number_of_pages = number_of_pages

    def __str__(self):
        return f"Book: {self.author_name} {self.author_surname}, {self.publication_date}, " \
               f"{self.number_of_pages} pages, {str(self.library)}"


class Order:
    def __init__(self, employee, student, books, order_date):
        self.employee = employee
        self.student = student
        self.books = books
        self.order_date = order_date

    def __str__(self):
        book_list = "\n".join([f"  - {str(book)}" for book in self.books])
        return f"Order by {str(self.employee)} for {str(self.student)} on {self.order_date}:\n{book_list}"


# Tworzenie instancji klas
library1 = Library("Cityville", "Main Street", "12345", "9:00 AM - 5:00 PM", "123-456-7890")
library2 = Library("Townsville", "Oak Street", "54321", "10:00 AM - 6:00 PM", "987-654-3210")

employee1 = Employee("Grzegorz", "Braun", "2022-01-01", "1990-05-15", "Cityville", "Main Street", "12345", "111-222-3333")
employee2 = Employee("Szymon", "Hołownia", "2022-02-01", "1988-08-20", "Townsville", "Oak Street", "54321", "444-555-6666")
employee3 = Employee("Gordon", "Ramsey", "2022-03-01", "1995-03-10", "Cityville", "Main Street", "12345", "777-888-9999")

book1 = Book(library1, "2021-01-15", "Author1", "Surname1", 200)
book2 = Book(library1, "2020-05-20", "Author2", "Surname2", 150)
book3 = Book(library2, "2019-11-10", "Author3", "Surname3", 300)
book4 = Book(library2, "2022-02-28", "Author4", "Surname4", 180)
book5 = Book(library2, "2020-09-05", "Author5", "Surname5", 250)

student1 = "Student1"
student2 = "Student2"
student3 = "Student3"

order1 = Order(employee1, student1, [book1, book2, book3], "2022-04-01")
order2 = Order(employee2, student2, [book4, book5], "2022-04-02")


print(order1)
print("\n-----------------------\n")
print(order2)