# -*- coding: utf-8 -*-
"""Oop_zad.3

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1Xc_0fMvExW9RG5uC34S7XPH3ULvHBXWg
"""

class Property:
    def __init__(self, area, rooms, price, address):
        self.area = area
        self.rooms = rooms
        self.price = price
        self.address = address

    def __str__(self):
        return f"Property: {self.area} sqm, {self.rooms} rooms, {self.price} USD, {self.address}"


class House(Property):
    def __init__(self, area, rooms, price, address, plot):
        super().__init__(area, rooms, price, address)
        self.plot = plot

    def __str__(self):
        return f"House - {super().__str__()}, Plot: {self.plot} sqm"


class Flat(Property):
    def __init__(self, area, rooms, price, address, floor):
        super().__init__(area, rooms, price, address)
        self.floor = floor

    def __str__(self):
        return f"Flat - {super().__str__()}, Floor: {self.floor}"



house1 = House(200, 5, 300000, "Kwiatowa 6", 500)
flat1 = Flat(80, 3, 120000, "Dworcowa 100", 2)


print(house1)
print("\n-----------------------\n")
print(flat1)