# -*- coding: utf-8 -*-
"""Zad.1

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1Xc_0fMvExW9RG5uC34S7XPH3ULvHBXWg
"""

def create_greeting(name, surname):
    if not isinstance(name, str) or not isinstance(surname, str):
        raise TypeError("Both arguments must be of type string")

    greeting = f"Cześć {name} {surname}!"
    return greeting
try:
    name_input = input("Podaj imię: ")
    surname_input = input("Podaj nazwisko: ")

    result = create_greeting(name_input, surname_input)
    print(result)
except TypeError as e:
    print(f"Błąd: {e}")