# -*- coding: utf-8 -*-
"""Zad.4

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1Xc_0fMvExW9RG5uC34S7XPH3ULvHBXWg
"""

def is_even(number):
    if not isinstance(number, int):
        raise TypeError("Argument must be of type int")

    return number % 2 == 0

# Przykład użycia funkcji
try:
    input_number = int(input("Podaj liczbę całkowitą: "))

    result = is_even(input_number)

    if result:
        print("Liczba parzysta")
    else:
        print("Liczba nieparzysta")
except ValueError:
    print("Podano nieprawidłową liczbę całkowitą.")
except TypeError as e:
    print(f"Błąd: {e}")