# -*- coding: utf-8 -*-
"""Zad.5

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1Xc_0fMvExW9RG5uC34S7XPH3ULvHBXWg
"""

def check_value_in_list(input_list, value):
    if not isinstance(input_list, list) or not isinstance(value, int):
        raise TypeError("First argument must be of type list, and the second must be of type int")

    return value in input_list

# Przykład użycia funkcji
try:
    input_list = [6, 64, 8, 15, 100]
    value_to_check = int(input("Podaj wartość do sprawdzenia w liście: "))

    result = check_value_in_list(input_list, value_to_check)

    if result:
        print(f"Lista zawiera wartość {value_to_check}.")
    else:
        print(f"Lista nie zawiera wartości {value_to_check}.")
except ValueError:
    print("Podano nieprawidłową wartość.")
except TypeError as e:
    print(f"Błąd: {e}")