# -*- coding: utf-8 -*-
"""Zadanie 2: b

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1N-6zjUhc6Yeha8m6bYFJoCqg1FuYSB5D
"""

def pomnoz_przez_dwa_for(lista_liczb):
    wynik = []
    for liczba in lista_liczb:
        wynik.append(liczba * 2)
    return wynik

lista_liczb = [8, 64, 12, 0, 5]
wynik_for = pomnoz_przez_dwa_for(lista_liczb)
print(wynik_for)

def pomnoz_przez_dwa_list_comprehension(lista_liczb):
    return [liczba * 2 for liczba in lista_liczb]

lista_liczb = [8, 64, 12, 40, 5]
wynik_list_comprehension = pomnoz_przez_dwa_list_comprehension(lista_liczb)
print(wynik_list_comprehension)