# -*- coding: utf-8 -*-
"""Zadanie 2: a

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1N-6zjUhc6Yeha8m6bYFJoCqg1FuYSB5D
"""

def wyswietl_imiona(imiona):
    if len(imiona) == 5:
        for imie in imiona:
            print(imie)
    else:
        print("Podano niewłaściwą liczbę imion. Oczekiwano 5 imion.")

lista_imion = ["Grzegorz", "Barbara", "Szymon", "Sebastian", "Katarzyna"]
wyswietl_imiona(lista_imion)