# -*- coding: utf-8 -*-
"""Zadanie 2: c

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1N-6zjUhc6Yeha8m6bYFJoCqg1FuYSB5D
"""

def wyswietl_parzyste_elementy(lista_liczb):
    for liczba in lista_liczb:
        if liczba % 2 == 0:
            print(liczba)

lista_liczb_parzystych = list(range(0, 20, 2))
wyswietl_parzyste_elementy(lista_liczb_parzystych)